### ISSUE TITLE
TODO Features

### ISSUE THREAD

**Issue by sidntrivedi** [vaibhavk/osdc-bots#9]
A Checklist of the features to be implemented:

- [x] Fetch list of upcoming NCR meetups using Meetup API.
- [ ] Add day to the meetups returned by the API.
- [ ] Add venue to the meetups returned by the API.
- [x] Add next OSDC Meetup details by admin.
- [ ] Add regex check to the meetup details.
- [x] Get next OSDC Meetup details.
- [ ] Save important articles/links for future reference.
- [ ] Kick the user who doesn't introduce within 48 hrs.
- [ ] Urban dictionary feature?
- [ ] OSDC tweet alert feature?
- [ ] Meetups/ CC Repo Alerts.
- [ ] gify api which returns gif by injecting a word?

Further suggestions are most welcome.
